// src/theme/theme.ts
export const themes = {
  dark: {
    bg: "#1e1e1e",
    bgPanel: "#252526",
    bgSidebar: "#252526",
    bgTopBar: "#3c3c3c",
    bgTab: "#2d2d2d",
    bgTabActive: "#1e1e1e",
    bgButton: "#0e639c",
    bgButtonHover: "#1177bb",
    bgHover: "#2a2d2e",
    bgSelected: "#37373d",
    bgOutput: "#1e1e1e",
    bgStatusBar: "#007acc",
    bgInput: "#3c3c3c",
    text: "#cccccc",
    textMuted: "#858585",
    textActive: "#ffffff",
    textOutput: "#4ec9b0",
    border: "#3c3c3c",
    borderActive: "#007acc",
    accent: "#007acc",
    accentHover: "#0098ff",
    error: "#f44747",
    warning: "#cca700",
    success: "#4ec9b0",
    scrollbar: "#424242",
    scrollbarHover: "#686868",
    fontMono: "'JetBrains Mono', 'Fira Code', 'Cascadia Code', monospace",
    fontUI: "'Segoe UI', system-ui, sans-serif",
  },
  light: {
    bg: "#ffffff",
    bgPanel: "#f3f3f3",
    bgSidebar: "#f3f3f3",
    bgTopBar: "#dddddd",
    bgTab: "#ececec",
    bgTabActive: "#ffffff",
    bgButton: "#0e639c",
    bgButtonHover: "#1177bb",
    bgHover: "#e8e8e8",
    bgSelected: "#d6ebff",
    bgOutput: "#f9f9f9",
    bgStatusBar: "#007acc",
    bgInput: "#ffffff",
    text: "#1f1f1f",
    textMuted: "#6e6e6e",
    textActive: "#000000",
    textOutput: "#007acc",
    border: "#d4d4d4",
    borderActive: "#007acc",
    accent: "#007acc",
    accentHover: "#005a9e",
    error: "#cd3131",
    warning: "#bf8803",
    success: "#14532d",
    scrollbar: "#c1c1c1",
    scrollbarHover: "#a8a8a8",
    fontMono: "'JetBrains Mono', 'Fira Code', 'Cascadia Code', monospace",
    fontUI: "'Segoe UI', system-ui, sans-serif",
  },
};

export type ThemeKey = keyof typeof themes;
export type Theme = (typeof themes)["dark"];